services:
  - type: web
    name: financial-ai-hub
    env: node
    plan: free
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: NODE_ENV=production node --optimize_for_size --max_old_space_size=460 app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CHATBOT_PORT
        value: 8001
      - key: RENDER_STORAGE_PATH
        sync: false
      - key: PYTHON_PATH
        value: python3
      - key: TZ
        value: UTC
      - key: SESSION_SECRET
        generateValue: true
      - key: UV_THREADPOOL_SIZE
        value: 1
      - key: NODE_OPTIONS
        value: --optimize_for_size --max_old_space_size=460
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
