services:
  - type: web
    name: financial-ai-hub
    env: node
    plan: free
    buildCommand: |
      chmod +x start.sh
      npm install compression --save
      npm install && pip install -r requirements.txt    startCommand: bash ./start.sh
    healthCheckPath: /healthz
    healthCheckTimeout: 300
    startupDelay: 120
    envVars:
      - key: NODE_ENV
        value: production
      - key: CHATBOT_PORT
        value: 8001
      - key: RENDER_STORAGE_PATH
        value: /data
      - key: PYTHON_PATH
        value: python3
      - key: TZ
        value: UTC
      - key: SESSION_SECRET
        generateValue: true
      - key: UV_THREADPOOL_SIZE
        value: 1
      - key: NODE_OPTIONS
        value: --optimize_for_size --max_old_space_size=460
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
