services:
  - type: web
    name: financial-ai-hub
    env: node
    buildCommand: npm install -g pm2 && npm install && pip install -r requirements.txt
    startCommand: bash start.sh    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER_STORAGE_PATH
        sync: false
      - key: PYTHON_PATH
        value: python3
      - key: TZ
        value: UTC
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
